### ISSUE TITLE
Android Camera Dependencies

### ISSUE THREAD

**Issue by carlitos-206** [invisement/easy-speak-app#37]
The camera isn't connecting properly with the code, unsure whether it's due to it being a VM Android. I have a physical android that I will try to connect with the app and test it and see if it works on a physical device 

Error:
`I/CameraManagerGlobal(10328): Connecting to camera service
I/xample.easy_app(10328): Compiler allocated 4533KB to compile void android.view.ViewRootImpl.performTraversals()
The Flutter DevTools debugger and profiler on sdk gphone64 x86 64 is available at: http://127.0.0.1:9103?uri=http://127.0.0.1:50804/ywEJTjFjaTw=/
W/Parcel  (10328): Expecting binder but got null!
D/CompatibilityChangeReporter(10328): Compat change id reported: 206033068; UID 10160; state: ENABLED
E/MethodChannel#plugins.flutter.io/camera_android(10328): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera_android(10328): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.plugins.camera.features.resolution.ResolutionFeature.configureResolution(ResolutionFeature.java:244)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.plugins.camera.features.resolution.ResolutionFeature.<init>(ResolutionFeature.java:50)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.plugins.camera.features.CameraFeatureFactoryImpl.createResolutionFeature(CameraFeatureFactoryImpl.java:58)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.plugins.camera.features.CameraFeatures.init(CameraFeatures.java:71)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.plugins.camera.Camera.<init>(Camera.java:217)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.plugins.camera.MethodCallHandlerImpl.instantiateCamera(MethodCallHandlerImpl.java:386)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.plugins.camera.MethodCallHandlerImpl.lambda$onMethodCall$0$io-flutter-plugins-camera-MethodCallHandlerImpl(MethodCallHandlerImpl.java:81)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.plugins.camera.MethodCallHandlerImpl$$ExternalSyntheticLambda0.onResult(Unknown Source:6)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.plugins.camera.CameraPermissions.requestPermissions(CameraPermissions.java:53)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:74)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)     
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)        
E/MethodChannel#plugins.flutter.io/camera_android(10328):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (10328): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(error, Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference)
E/flutter (10328): #0      AndroidCamera.createCamera (package:camera_android/src/android_camera.dart:112:7)
E/flutter (10328): <asynchronous suspension>
E/flutter (10328): #1      CameraController.initialize (package:camera/src/camera_controller.dart:295:19)
E/flutter (10328): <asynchronous suspension>
E/flutter (10328):`

**Comment by carlitos-206** [comment]
The camera is now working only issue is now getting permission to store image files on device incase we need to save files in a user device
